version: '3.7'

services:
  mongodb:
    image: mongo:3.6
    container_name: aop-mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./docker/mongo/db:/data/db
      - ./docker/mongo/initdb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_USERNAME: "${MONGO_INITDB_USERNAME}"
      MONGO_INITDB_PASSWORD: "${MONGO_INITDB_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
